In [56]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import check_random_state 
from sklearn.datasets import fetch_mldata
from sklearn.neural_network import MLPClassifier
from sklearn import metrics

In [2]:
mnist =fetch_mldata('MNIST original')


In [3]:
x=mnist.data.astype('float64')
y=mnist.target.astype('float64')

In [4]:
random_state = check_random_state(0)
permutation = random_state.permutation(x.shape[0])

In [5]:
x=x[permutation]
y=y[permutation]
x = x.reshape((x.shape[0], -1))

In [6]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=10000, test_size=5000)

In [7]:
scaler=StandardScaler()

In [8]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [35]:
clf = MLPClassifier(solver='sgd', alpha=1e-4,activation='logistic',hidden_layer_sizes=(10, 10), random_state=1,
                    max_iter=1000,tol=1e-4,learning_rate_init=.1)

In [36]:
clf.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10), learning_rate='constant',
       learning_rate_init=0.1, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [37]:
clf.score(x_test,y_test)

0.8724

In [38]:
clf = MLPClassifier(solver='sgd', alpha=1e-4,activation='logistic',hidden_layer_sizes=(10, 10,10), random_state=1,
                    max_iter=1000,tol=1e-4,learning_rate_init=.1)

In [39]:
clf.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.1, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [40]:
clf.score(x_test,y_test)

0.8274

In [41]:
clf = MLPClassifier(solver='sgd', alpha=1e-4,activation='logistic',hidden_layer_sizes=(20, 20), random_state=1,
                    max_iter=1000,tol=1e-4,learning_rate_init=.1)

In [42]:
clf.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(20, 20), learning_rate='constant',
       learning_rate_init=0.1, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [43]:
clf.score(x_test,y_test)

0.9078

In [44]:
clf = MLPClassifier(solver='sgd', alpha=1e-4,activation='logistic',hidden_layer_sizes=(50, 50), random_state=1,
                    max_iter=1000,tol=1e-4,learning_rate_init=.1)

In [45]:
clf.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 50), learning_rate='constant',
       learning_rate_init=0.1, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [46]:
clf.score(x_test,y_test)

0.9298

In [47]:
clf = MLPClassifier(solver='sgd', alpha=1e-4,activation='logistic',hidden_layer_sizes=(70, 70), random_state=1,
                    max_iter=1000,tol=1e-4,learning_rate_init=.1)

In [48]:
clf.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(70, 70), learning_rate='constant',
       learning_rate_init=0.1, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [49]:
clf.score(x_test,y_test)

0.9366

In [50]:
clf = MLPClassifier(solver='sgd', alpha=1e-4,activation='logistic',hidden_layer_sizes=(100, 100), random_state=1,
                    max_iter=1000,tol=1e-4,learning_rate_init=.1)

In [51]:
clf.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100), learning_rate='constant',
       learning_rate_init=0.1, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [52]:
clf.score(x_test,y_test)

0.935

In [53]:
clf = MLPClassifier(solver='sgd', alpha=1e-4,activation='relu',hidden_layer_sizes=(100, 100), random_state=1,
                    max_iter=1000,tol=1e-4,learning_rate_init=.1)

In [54]:
clf.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100), learning_rate='constant',
       learning_rate_init=0.1, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [55]:
clf.score(x_test,y_test)

0.9498

In [57]:
y_pred=clf.predict(x_test)
kkk=metrics.classification_report(y_test, y_pred)

In [58]:
print(kkk)

             precision    recall  f1-score   support

        0.0       0.98      0.97      0.98       518
        1.0       0.97      0.97      0.97       524
        2.0       0.92      0.97      0.94       467
        3.0       0.95      0.94      0.94       504
        4.0       0.95      0.96      0.95       559
        5.0       0.94      0.91      0.92       435
        6.0       0.96      0.96      0.96       501
        7.0       0.95      0.93      0.94       511
        8.0       0.94      0.93      0.94       510
        9.0       0.94      0.95      0.95       471

avg / total       0.95      0.95      0.95      5000



In [61]:
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

[[504   0   1   0   0   3   4   1   4   1]
 [  0 509   3   3   1   1   3   1   3   0]
 [  1   2 452   2   1   0   0   5   4   0]
 [  0   2  11 472   1   8   0   4   4   2]
 [  2   5   4   0 535   1   3   2   2   5]
 [  1   1   2  14   2 394   8   4   6   3]
 [  3   1   3   0   6   2 483   0   3   0]
 [  1   2   7   2   9   0   0 476   1  13]
 [  2   3   6   3   3   9   2   3 475   4]
 [  1   2   1   1   8   0   0   7   2 449]]
