In [30]:
import numpy as np
import matplotlib as plt
from sklearn.datasets import fetch_mldata
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import check_random_state 
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [2]:
mnist =fetch_mldata('MNIST original')

In [3]:
mnist


{'COL_NAMES': ['label', 'data'],
 'DESCR': 'mldata.org dataset: mnist-original',
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'target': array([0., 0., 0., ..., 9., 9., 9.])}

In [4]:
x=mnist.data.astype('float64')

In [5]:
y=mnist.target.astype('float64')

In [6]:
random_state = check_random_state(0)

In [7]:
permutation = random_state.permutation(x.shape[0])

In [8]:
x=x[permutation]

In [9]:
y=y[permutation]

In [10]:
x.shape

(70000, 784)

In [11]:
x = x.reshape((x.shape[0], -1))

In [12]:
x.shape

(70000, 784)

In [13]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=10000, test_size=5000)

In [14]:
scaler=standardscaler()


NameError: name 'standardscaler' is not defined

In [15]:
scaler=StandardScaler()

In [16]:
x_train=scaler.fit_transform(x_train)

In [17]:
x_test=scaler.transform(x_test)

In [18]:
clf = LogisticRegression(C=0.1,
                         multi_class='multinomial',
                         penalty='l1', solver='saga', tol=0.1)

In [19]:
clf.fit(x_train,y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=1, penalty='l1', random_state=None, solver='saga',
          tol=0.1, verbose=0, warm_start=False)

In [20]:
score=clf.score(x_test,y_test)

In [21]:
print(score)

0.8876


In [22]:
sparsity = np.mean(clf.coef_ == 0) * 100

In [23]:
#what does this mean here????????????????????/
print(sparsity)

25.357142857142854


In [25]:
y_pred = clf.predict(x_test)
cm = confusion_matrix(y_test, y_pred)

In [26]:
print(cm)

[[453   0   1   3   1   6   7   0   2   0]
 [  0 576   3   1   0   4   1   1   6   0]
 [  3   9 438  15   9   1   9  14  10   4]
 [  1  13  15 426   1  16   4   7  14   5]
 [  1   5   1   1 476   3   3   1   2  31]
 [  5   8   2  23  13 354  10   1  13   7]
 [  2   5   5   0   2  10 440   0   3   0]
 [  3  10   3   2   9   1   0 456   1  24]
 [  7  23   8  16   6  20   6   4 383   9]
 [  7   7   2   7  20   1   0  22   1 436]]


In [31]:

y_pred=clf.predict(x_test)
kkk=metrics.classification_report(y_test, y_pred)

In [32]:
print(kkk)

             precision    recall  f1-score   support

        0.0       0.94      0.96      0.95       473
        1.0       0.88      0.97      0.92       592
        2.0       0.92      0.86      0.88       512
        3.0       0.86      0.85      0.86       502
        4.0       0.89      0.91      0.90       524
        5.0       0.85      0.81      0.83       436
        6.0       0.92      0.94      0.93       467
        7.0       0.90      0.90      0.90       509
        8.0       0.88      0.79      0.84       482
        9.0       0.84      0.87      0.86       503

avg / total       0.89      0.89      0.89      5000

