In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import check_random_state 
from sklearn.datasets import fetch_mldata
from sklearn import metrics

In [2]:
mnist =fetch_mldata('MNIST original')

In [3]:
x=mnist.data.astype('float64')
y=mnist.target.astype('float64')

In [4]:
random_state = check_random_state(0)

In [5]:
permutation = random_state.permutation(x.shape[0])

In [6]:
x=x[permutation]
y=y[permutation]
x = x.reshape((x.shape[0], -1))

In [7]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=10000, test_size=5000)

In [8]:
scaler=StandardScaler()

In [9]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [10]:
clf=svm.SVC(C=.1,decision_function_shape='ovo')

In [11]:
clf.fit(x_train,y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
score=clf.score(x_test,y_test)

In [13]:
print(score)

0.8728


In [14]:
clf=svm.SVC(C=.1,decision_function_shape='ovr',gamma=0.001)

In [15]:
clf.fit(x_train,y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
score=clf.score(x_test,y_test)

In [17]:
print(score)

0.8776


In [18]:
y_pred=clf.predict(x_test)

In [19]:
kkk=metrics.classification_report(y_test, y_pred)

In [20]:
print(kkk)

             precision    recall  f1-score   support

        0.0       0.95      0.94      0.95       520
        1.0       0.93      0.98      0.95       560
        2.0       0.73      0.89      0.80       510
        3.0       0.89      0.81      0.85       506
        4.0       0.91      0.88      0.89       482
        5.0       0.87      0.83      0.85       433
        6.0       0.94      0.90      0.92       525
        7.0       0.89      0.86      0.88       525
        8.0       0.87      0.81      0.84       495
        9.0       0.82      0.85      0.84       444

avg / total       0.88      0.88      0.88      5000



In [21]:
kk=metrics.confusion_matrix(y_test, y_pred)


In [22]:
print(kk)

[[489   0   6   4   2   6   6   0   6   1]
 [  0 551   4   1   1   1   0   0   2   0]
 [  8   7 455   5   5   1   4   6  18   1]
 [  1   7  41 408   1  12   1  14  16   5]
 [  2   2  19   0 422   0   3   3   2  29]
 [  3   5  20  15   4 360  11   0  10   5]
 [  4   2  31   0   2  10 471   1   4   0]
 [  0  10  20   1  13   0   0 453   0  28]
 [  3  10  20  15   2  23   3   4 401  14]
 [  3   0   9   9  11   2   0  29   3 378]]


In [23]:
clf=svm.SVC(C=1,decision_function_shape='ovr',gamma=0.001)

In [24]:
clf.fit(x_train,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
score=clf.score(x_test,y_test)

In [26]:
print(score)

0.9364


In [27]:
y_pred=clf.predict(x_test)

In [28]:
kkk=metrics.classification_report(y_test, y_pred)

In [29]:
print(kkk)

             precision    recall  f1-score   support

        0.0       0.97      0.97      0.97       520
        1.0       0.97      0.99      0.98       560
        2.0       0.89      0.95      0.92       510
        3.0       0.93      0.89      0.91       506
        4.0       0.96      0.93      0.94       482
        5.0       0.93      0.90      0.91       433
        6.0       0.95      0.96      0.96       525
        7.0       0.94      0.93      0.93       525
        8.0       0.92      0.92      0.92       495
        9.0       0.91      0.90      0.90       444

avg / total       0.94      0.94      0.94      5000



In [30]:
kk=metrics.confusion_matrix(y_test, y_pred)


In [31]:
print(kk)

[[505   0   2   2   2   2   4   0   3   0]
 [  0 553   3   0   0   0   1   0   2   1]
 [  5   3 486   2   1   0   3   2   7   1]
 [  2   4  17 452   1   9   1   9  11   0]
 [  2   0  10   1 449   0   2   1   0  17]
 [  0   2   7  10   4 390   9   1   8   2]
 [  2   1   6   0   0   7 505   1   3   0]
 [  0   5   8   1   5   0   0 489   0  17]
 [  1   4   6   9   2  10   4   3 453   3]
 [  3   0   4   9   6   2   0  16   4 400]]
